services:

  # Console commands
  Pada\RequestBodyBundle\Command\DebugCommand:
    public: true
    calls:
      - setScanDir: [ '%kernel.project_dir%/src' ]
      - setReflectionScanner: [ '@reflection_scanner' ]
    tags:
      - { name: 'console.command', command: 'debug:request-body' }

  # Common services
  reflection_scanner:
    class: Pada\Reflection\Scanner\Scanner
    arguments: ['@annotations.reader']

  request_body_service:
    class: Pada\RequestBodyBundle\Service\RequestBodyService
    arguments: ['@annotations.reader', '@serializer', '@validator']

  Pada\RequestBodyBundle\EventListener\RequestBodyListener:
    arguments: ['@request_body_service']
    tags:
      - { name: kernel.event_listener, event: kernel.controller, priority: 240 }

  Pada\RequestBodyBundle\ArgumentResolver\RequestBodyResolver:
    arguments: ['@request_body_service']
    tags:
      - { name: controller.argument_value_resolver, priority: 240 }
